services:
  client:
    build: ./client
    container_name: client_container
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=            
      - NODE_ENV=development  
      - VITE_PROXY_TARGET=http://server_container:4000        
    networks:
      - closestcloset
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build: ./server
    container_name: server_container
    ports:
      - '4000:4000'
    networks:
      - closestcloset
    environment:
      REDIS_URL: redis://redis_container:6379  
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
      - redis

  chatbot:
    build: ./chatbot
    container_name: chatbot_container
    ports:
      - "8000:8000"
    env_file:
      - ./chatbot/.env
    environment:
      REDIS_URL: redis://redis_container:6379
    volumes:
      - ./chatbot:/app
    depends_on:
      - redis
    networks:
      - closestcloset

  db:
    image: mongo:7.0-jammy
    container_name: db_container
    restart: always
    # environment:
    #   MONGO_INITDB_DATABASE: closestcloset
    volumes:
      - mongo_data:/data/db
    networks:
      - closestcloset

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - closestcloset

version: '3.8'

volumes:
  mongo_data:
    driver: local
  redis_data:

networks:
  closestcloset:
    driver: bridge

